# -*- coding: utf-8 -*-
"""8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pkCAFO1JGmvBS6ErebyqwUJZdNiVv7e3
"""

X=90
name="Ashiq"
print("X value:", X)
print("name value:",name)
print("X type:",type(X))
print("name type:",type(name))